### ISSUE TITLE
M420 after G29

### ISSUE THREAD

**Issue by Eslmatt** [teachingtechYT/teachingtechYT.github.io#260] opened 2021-02-16 20:24 UTC
In the downloaded gcode for all gcode prints you have 
G29; ABL
M420 S1; restore ABL mesh

This seems to completely disable the new probe. Removing the M420 has solved my bed leveling problems. It would be easier if beginners don't have to dig into all this to figure out what is going wrong, and not make the mistake I made and copy that into my start Gcode ;)

[https://marlinfw.org/docs/features/auto_bed_leveling.html](https://marlinfw.org/docs/features/auto_bed_leveling.html)
Saving and Loading
After a G29 the leveling data is only stored in RAM. You have to use M500 to save the bed leveling data to EEPROM, otherwise the data will be lost when you restart (or reconnect) the printer. Use M502 to reset the bed leveling data (and other settings to defaults). Use M501 to reload your last-saved bed leveling from EEPROM. This is done automatically on reboot.

After a G29 bed leveling is automatically enabled, but in all other situations you must use M420 S1 to enable bed leveling. It is essential to include the command M420 S1 in the “Start G-code” in your slicer settings. If you have no bed leveling, or if there is no leveling data, then this command is simply ignored.

**Comment by teachingtechYT** [comment] 2021-07-13 09:57
The source gcode starts with both of these commented out. Depending on what the user selects from the dropdown, one or the other is then uncommented. I have been through every ABL option and I can't reproduce your steps. Are you sure you didn't subconsciously remove the semi colon when transferring to your slicer?
This is the only ever report of this from thousands of users too.
Please reopen if you can reproduce the problem.

**Closed by teachingtechYT** 2021-07-13 09:57 UTC
