### ISSUE TITLE
TemperatureTowerV2 Slicing

### ISSUE THREAD

**Issue by porter75** [teachingtechYT/teachingtechYT.github.io#355] opened 2021-08-23 15:28 UTC
I am using a CR-6 SE. I just replaced the nozzle, the tube is now Capricorn, and I've also replaced the stock extruder with an all metal one.

The TemperatureTowerV2 print gets about half way through printing the first temperature level and the overhang on the right starts to pile up and curl upwards. The nozzle keeps depositing material on this lip and it eventually catches and rips the print off the bed. I thought it was an over extrusion problem at first, but I was able to print a CHEP cube that I sliced without issue. See the attached images of the gcode in Cura that may shed some more light on the issue. It would appear to be the layer lines on the new temperature tower are too far apart from one another. This is causing them not to adhere to one another and giving me issues. It looks like some sort of slicing error. I'm currently printing the one I sliced myself in Cura and it is about to complete the first temperature level with only some minor stringing.

![TeachingTech Sliced TempTower](https://user-images.githubusercontent.com/89404766/130473776-a209072e-03ca-437b-ae43-6f18a3572424.jpg)
![Cura Sliced TempTower](https://user-images.githubusercontent.com/89404766/130473794-321e2d50-3bdd-4796-b908-0f8f63ba8225.jpg)

**Comment by teachingtechYT** [comment] 2021-08-31 01:04
This looks like a duplicate of #349 
The default profile in Cura has layer time auto slow down on whereas my site doesn't. Putting the speed setting much lower for the site will match what your Cura profile is producing and let the part cooling catch up.

**Closed** 2021-09-01 23:38 UTC
