### ISSUE TITLE
Gcode with too long numbers make the printer reset

### ISSUE THREAD

**Issue by frmelle** [teachingtechYT/teachingtechYT.github.io#267] opened 2021-02-25 21:16 UTC
Using generated Gcode make my printer reset after 1 or 2 minutes of print time.

Reason is that the commands are too long :

`G1 X137.82299999999998 Y112.987 E0.0373`
`G1 X137.945 Y112.75800000000001 E0.0466`
`G1 X138.091 Y112.543 E0.0560`
`G1 X138.25900000000001 Y112.345 E0.0653`
`G1 X138.447 Y112.166 E0.0746`
`G1 X138.654 Y112.009 E0.0839`
`G1 X138.877 Y111.875 E0.0933`
`G1 X139.112 Y111.76599999999999 E0.1026`

If I replace too long numbers after decimal with round up ones to maximum 3 or 4 digits as decimal, it works without any problem
`G1 X137.823 Y112.987 E0.0373`
`G1 X137.945 Y112.758 E0.0466`
`G1 X138.091 Y112.543 E0.0560`
`G1 X138.259 Y112.345 E0.0653`
`G1 X138.447 Y112.166 E0.0746`
`G1 X138.654 Y112.009 E0.0839`
`G1 X138.877 Y111.875 E0.0933`
`G1 X139.112 Y111.766 E0.1026`

It should not be very difficult to correct this.

Thank-you.

**Comment by ryamoo** [comment] 2021-07-13 07:12
Duplicate of #241

**Closed** 2021-07-13 10:06 UTC
